# Generated by Django 2.2.4 on 2019-12-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_friendrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='friend_since',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following_since',
            field=models.DateTimeField(default=None),
        ),
    ]
