# Generated by Django 2.2.4 on 2019-12-19 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191218_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequests',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
