# Generated by Django 2.2.4 on 2019-12-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191219_0353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequests',
            unique_together={('user_from', 'user_to')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following')},
        ),
    ]
