# Generated by Django 2.2.4 on 2019-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
