# Generated by Django 2.2.4 on 2019-12-06 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_creator', models.CharField(max_length=100)),
                ('repo_language', models.CharField(max_length=50)),
                ('repo_name', models.CharField(max_length=200)),
                ('repo_description', models.CharField(max_length=500)),
                ('repo_url', models.URLField()),
                ('repo_stars', models.IntegerField()),
                ('repo_score', models.IntegerField()),
                ('repo_watchers', models.IntegerField()),
                ('repo_created_on', models.DateTimeField()),
                ('is_favorited', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
