# Generated by Django 5.1.4 on 2025-03-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_creator", models.CharField(max_length=100)),
                ("repo_language", models.CharField(max_length=50)),
                ("repo_name", models.CharField(max_length=200, unique=True)),
                ("repo_description", models.CharField(max_length=500)),
                ("repo_url", models.URLField()),
                ("repo_stars", models.IntegerField()),
                ("repo_score", models.IntegerField()),
                ("repo_watchers", models.IntegerField()),
                ("repo_created_on", models.DateTimeField()),
                ("repo_forked", models.IntegerField(default=0)),
                ("is_favorited", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepoUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("user_url", models.URLField()),
                ("user_image_url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_user_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
