# Generated by Django 2.2.4 on 2019-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='repo_forked',
            field=models.IntegerField(default=0),
        ),
    ]
