# Generated by Django 2.2.4 on 2019-12-07 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github', '0002_repomodel_repo_forked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_repo_url', models.URLField()),
                ('user_url', models.URLField()),
                ('user_image_url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
