# Generated by Django 2.2.4 on 2019-12-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_repousermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repousermodel',
            name='user_repo_url',
        ),
    ]
