# Generated by Django 2.2.4 on 2019-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_repotopicmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repomodel',
            name='repo_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='repotopicmodel',
            name='topic_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='repousermodel',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
